//
// $Id$

package com.whirled.game.data;

/**
 * Constants related to whirled games.
 */
public interface WhirledGameCodes
{
    /** The message bundle for whirledgame stuff. */
    public static final String WHIRLEDGAME_MESSAGE_BUNDLE = "whirledgame";

    /** A chat localtype indicating that the message was generated by usercode and
     * not by the whirled game framework. */
    public static final String USERGAME_CHAT_TYPE = "usergame";
}
