//
// $Id$

package com.whirled.game.data {

/**
 * Constants related to whirled games.
 */
public class WhirledGameCodes
{
    /** The message bundle for whirledgame stuff. */
    public static const WHIRLEDGAME_MESSAGE_BUNDLE :String = "whirledgame";

    /** A chat localtype indicating that the message was generated by usercode and
     * not by the whirled game framework. */
    public static const USERGAME_CHAT_TYPE :String = "usergame";
}
}
